// angular/i_routing_one/src/app/components/contactform.component.ts
import { Component } from "@angular/core";
import { Contact } from "../models/contact.model";
import { FormsModule } from "@angular/forms";
import { ContactService } from "../services/contact.service";

@Component({
  selector: "contact-form",
  standalone: true,
  imports: [FormsModule],
  templateUrl: "./contactform.component.html"
})
export class ContactForm {
  contact = new Contact("", "", "", "", 0);

  constructor(private contactService: ContactService) {}

  addContact() {
    this.contactService.addContact(this.contact);
    this.contact = new Contact("", "", "", "", 0);
  }
}
<form (ngSubmit)="addContact()" #contactForm="ngForm">
  <label for="firstname">First name</label>
  <input type="text" name="firstname" id="firstname" [(ngModel)]="contact.firstname" />
  <br />
  <label for="lastname">Last name</label>
  <input type="text" name="lastname" id="lastname" [(ngModel)]="contact.lastname" />
  <br />
  <label for="email">Email</label>
  <input type="email" name="email" id="email" [(ngModel)]="contact.email" />
  <br />
  <label for="phone">Phone</label>
  <input type="tel" name="phone" id="phone" [(ngModel)]="contact.phone" />
  <br />
  <input type="submit" value="Add Contact" />
</form>

// react/05_lists/src/components/ContactForm.tsx
import React, { useState } from "react";
import Contact from "../models/Contact";

interface State {
  firstname: string;
  lastname: string;
  email: string;
  phone: string;
}

interface Props {
  addContact(contact: Contact): void;
}

const ContactForm = (props: Props) => {
  const [state, setState] = useState<State>({
    firstname: "",
    lastname: "",
    email: "",
    phone: ""
  })

  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setState((state) => {
      return {
        ...state,
        [event.target.name]: event.target.value
      }
    })
  }

  const onSubmit = (event: React.SyntheticEvent) => {
    event.preventDefault();
    if (!state.firstname || !state.lastname || !state.email || !state.phone) {
      return;
    }
    const contact = new Contact(
        state.firstname, state.lastname, state.email, state.phone, 0
    );
    props.addContact(contact);
    setState({
      firstname: "",
      lastname: "",
      email: "",
      phone: ""
    })
  }

  return (
    <div style={{ width: "16%", margin: "auto" }}>
      <form onSubmit={onSubmit}>
        <label htmlFor="firstname">Firstname </label>
        <input 
          type="text" 
          name="firstname" 
          id="firstname" 
          onChange={onChange} 
          value={state.firstname} />
        <br />
        <label htmlFor="lastname">Lastname </label>
        <input 
          type="text" 
          name="lastname" 
          id="lastname" 
          onChange={onChange} 
          value={state.lastname} />
        <br />
        <label htmlFor="email">Email </label>
        <input 
          type="email" 
          name="email" 
          id="email" 
          onChange={onChange} 
          value={state.email} />
        <br />
        <label htmlFor="phone">Phone </label>
        <input 
          type="tel" 
          name="phone" 
          id="phone" 
          onChange={onChange} 
          value={state.phone} />
        <br />
        <button type="submit">Add Contact</button>
      </form>
    </div>
  )
}

export default ContactForm;
