// angular/i_routing_one/src/app/components/contactlist.component.ts
import { CommonModule } from "@angular/common";
import { Component, OnInit } from "@angular/core";
import { ContactService } from "../services/contact.service";
import { Contact } from "../models/contact.model";

@Component({
    selector: "contact-list",
    standalone: true,
    imports: [CommonModule],
    templateUrl: "./contactlist.component.html"
})
export class ContactList implements OnInit {
    contactList: Contact[] = [];

    constructor(private contactService: ContactService) {}

    ngOnInit() {
      this.getList();
    }

    getList() {
      this.contactList = this.contactService.getList();
    }

    removeContact(id: number) {
      this.contactService.removeContact(id);
      this.getList();
    }
}
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Remove</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let c of contactList">
      <td>{{c.firstname}}</td>
      <td>{{c.lastname}}</td>
      <td>{{c.email}}</td>
      <td>{{c.phone}}</td>
      <td><button (click)="removeContact(c.id)">Remove</button></td>
    </tr>
  </tbody>
</table>

// react/05_lists/src/components/ContactList.tsx
import Contact from "../models/Contact";

interface Props {
  list: Contact[];
  removeContact(id: number): void;
}

const ContactList = (props: Props) => {
  const contactJSX = props.list.map((contact) => {
    return (
      <tr key={contact.id}>
        <td>{contact.firstname}</td>
        <td>{contact.lastname}</td>
        <td>{contact.email}</td>
        <td>{contact.phone}</td>
        <td>
          <button 
            onClick={() => props.removeContact(contact.id)}
            style={{ backgroundColor: "red"}}>
              Remove
          </button>
        </td>
      </tr>
    )
  })

  return (
    <table style={{ width: "16%", margin: "auto" }}>
      <thead>
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Email</th>
          <th>Phone</th>
        </tr>
      </thead>
      <tbody>
        {contactJSX}
      </tbody>
    </table>
  )
}

export default ContactList;
